version: '3'
name: "chatbot"


services:
  db:
    container_name: db
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE     : ChatbotMemoryDB
      MYSQL_USER         : dbuser
      MYSQL_PASSWORD     : qwerty
    ports:
      - "3306:3306"
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - bridgenetwork
    restart: always

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    networks:
      - bridgenetwork
    restart: always

  query_retriever:
    container_name: query_retriever
    build:
      context: ./query_retriever
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - db
    environment:
      DATABASE_HOST    : db
      DATABASE_USER    : query_retriever
      DATABASE_PASSWORD: qwerty
      DATABASE_NAME    : ChatbotMemoryDB
    networks:
      - bridgenetwork
    restart: always

  db_retriever:
    container_name: db_retriever
    build:
      context: ./db_retriever
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - db
    environment:
      DATABASE_HOST    : db
      DATABASE_USER    : db_retriever
      DATABASE_PASSWORD: qwerty
      DATABASE_NAME    : ChatbotMemoryDB
    networks:
      - bridgenetwork
    restart: always

  reply_generator:
    container_name: reply_generator
    build:
      context: ./reply_generator
      dockerfile: Dockerfile
    ports:
      - "5004:8080"
    depends_on:
      - db
    environment:
      DATABASE_HOST    : db
      DATABASE_USER    : reply_generator
      DATABASE_PASSWORD: qwerty
      DATABASE_NAME    : ChatbotMemoryDB
    networks:
      - bridgenetwork
    restart: always

  phpmyadmin:
    container_name: phpmyadmin  
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 6660:80
    networks:
      - bridgenetwork
    restart: always

networks:
  bridgenetwork:
    driver: bridge
